load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "orderbook",
    srcs = ["order_book.cc"],
    hdrs = ["order_book.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//libs/marketdata",
        "@abseil-cpp//absl/container:btree",
        "@abseil-cpp//absl/container:flat_hash_map",
    ],
)

cc_test(
    name = "order_book_test",
    srcs = ["order_book_test.cc"],
    deps = [
        ":orderbook",
        "@googletest//:gtest_main",
    ],
)
